//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Category_Product = new HashSet<Category_Product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public byte[] image { get; set; }
    
        public virtual ICollection<Category_Product> Category_Product { get; set; }
    }
}
